# Generated by Django 4.0.3 on 2022-03-22 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0002_alter_article_author_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='desctiption',
            new_name='description',
        ),
    ]
